on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Publish version tags to maven central

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "VERSION=${TAG/v/}" >> $GITHUB_ENV
      - run: echo "Will start a Maven Central upload with tag ${VERSION}"

      - uses: actions/checkout@v2

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: 'zulu'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          cache: 'maven'

      - name: Publish package
        run: mvn --batch-mode clean deploy -DperformRelease=true -DskipTests=true -Dcheckstyle.skip
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
